In [1]:
import numpy as np

#For 1-D arrays
a = np.array([5,3.2,6,8,10,16.8,9,18,4.5,True,'Hello',False,0],dtype='object')
a

array([5, 3.2, 6, 8, 10, 16.8, 9, 18, 4.5, True, 'Hello', False, 0],
      dtype=object)

In [6]:
#insert before 3rd index and value is 'One'
np.insert(a,3,'One')

array([5, 3.2, 6, 'One', 8, 10, 16.8, 9, 18, 4.5, True, 'Hello', False, 0],
      dtype=object)

In [26]:
#insert before index 5 and 8
x=3+5j
np.insert(a,[5,8],x)

array([5, 3.2, 6, 8, 10, (3+5j), 16.8, 9, 18, (3+5j), 4.5, True, 'Hello',
       False, 0], dtype=object)

In [8]:
#insert 2 different values before index 5 and 8
np.insert(a,[5,8],['One','Two'])

array([5, 3.2, 6, 8, 10, 'One', 16.8, 9, 18, 'Two', 4.5, True, 'Hello',
       False, 0], dtype=object)

In [10]:
b = np.array([0,1,2,3,4,5,6])
b

array([0, 1, 2, 3, 4, 5, 6])

In [16]:
# insert with operation
np.insert(b,3,2+5)

array([0, 1, 2, 7, 3, 4, 5, 6])

In [24]:
# insert with float value, but string and complex will through error
np.insert(b,3,8.9)

array([0, 1, 2, 8, 3, 4, 5, 6])

In [27]:
# 2-D arrays
c = np.array([[13, 2, 3, 54], [15, 26, 17, 8], [39, 12, 78, 10]])
c

array([[13,  2,  3, 54],
       [15, 26, 17,  8],
       [39, 12, 78, 10]])

In [28]:
# insert value axis = None, 2-D array converted into 1-D array
np.insert(c,3,818)

array([ 13,   2,   3, 818,  54,  15,  26,  17,   8,  39,  12,  78,  10])

In [35]:
# insert value axis = 1 or -1, column wise inserted, with single value braodcasting is done
np.insert(c,3,818, axis = -1)

array([[ 13,   2,   3, 818,  54],
       [ 15,  26,  17, 818,   8],
       [ 39,  12,  78, 818,  10]])

In [40]:
# insert value axis = 0 or -2, row wise inserted
np.insert(c,3,[[81,82,83,84],[85,86,87,88]], axis = -2)

array([[13,  2,  3, 54],
       [15, 26, 17,  8],
       [39, 12, 78, 10],
       [81, 82, 83, 84],
       [85, 86, 87, 88]])

In [75]:
#Insert 3-D arrays
d = np.array([[[13, 2, 3, 54], [15, 26, 17, 8]], [[39, 12, 78, 10],[0, 1, 16, 77]]])
d

array([[[13,  2,  3, 54],
        [15, 26, 17,  8]],

       [[39, 12, 78, 10],
        [ 0,  1, 16, 77]]])

In [77]:
# insert value axis = 2 or -1, row wise inserted in 3-D array
np.insert(d,1,67,axis= 2)

array([[[13, 67,  2,  3, 54],
        [15, 67, 26, 17,  8]],

       [[39, 67, 12, 78, 10],
        [ 0, 67,  1, 16, 77]]])

In [71]:
np.insert(d,2,[81,82,83,84],axis= -3)

array([[[13,  2,  3, 54],
        [15, 26, 17,  8]],

       [[39, 12, 78, 10],
        [ 0,  1, 16, 77]],

       [[81, 82, 83, 84],
        [81, 82, 83, 84]]])

In [72]:
np.insert(d,1,66,axis= 1)

array([[[13,  2,  3, 54],
        [66, 66, 66, 66],
        [15, 26, 17,  8]],

       [[39, 12, 78, 10],
        [66, 66, 66, 66],
        [ 0,  1, 16, 77]]])

In [73]:
np.insert(d,1,66,axis= -2)

array([[[13,  2,  3, 54],
        [66, 66, 66, 66],
        [15, 26, 17,  8]],

       [[39, 12, 78, 10],
        [66, 66, 66, 66],
        [ 0,  1, 16, 77]]])

In [70]:
np.insert(d,1,555,axis= 0)

array([[[ 13,   2,   3,  54],
        [ 15,  26,  17,   8]],

       [[555, 555, 555, 555],
        [555, 555, 555, 555]],

       [[ 39,  12,  78,  10],
        [  0,   1,  16,  77]]])

In [97]:
# insert 4-D arrays
e = np.arange(72).reshape(4,3,2,3)
e

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]],


       [[[36, 37, 38],
         [39, 40, 41]],

        [[42, 43, 44],
         [45, 46, 47]],

        [[48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65]],

        [[66, 67, 68],
         [69, 70, 71]]]])

In [81]:
np.insert(e,1,555,axis= 0)

array([[[[  0,   1,   2],
         [  3,   4,   5]],

        [[  6,   7,   8],
         [  9,  10,  11]],

        [[ 12,  13,  14],
         [ 15,  16,  17]]],


       [[[555, 555, 555],
         [555, 555, 555]],

        [[555, 555, 555],
         [555, 555, 555]],

        [[555, 555, 555],
         [555, 555, 555]]],


       [[[ 18,  19,  20],
         [ 21,  22,  23]],

        [[ 24,  25,  26],
         [ 27,  28,  29]],

        [[ 30,  31,  32],
         [ 33,  34,  35]]],


       [[[ 36,  37,  38],
         [ 39,  40,  41]],

        [[ 42,  43,  44],
         [ 45,  46,  47]],

        [[ 48,  49,  50],
         [ 51,  52,  53]]],


       [[[ 54,  55,  56],
         [ 57,  58,  59]],

        [[ 60,  61,  62],
         [ 63,  64,  65]],

        [[ 66,  67,  68],
         [ 69,  70,  71]]]])

In [82]:
np.insert(e,1,555,axis= -2)

array([[[[  0,   1,   2],
         [555, 555, 555],
         [  3,   4,   5]],

        [[  6,   7,   8],
         [555, 555, 555],
         [  9,  10,  11]],

        [[ 12,  13,  14],
         [555, 555, 555],
         [ 15,  16,  17]]],


       [[[ 18,  19,  20],
         [555, 555, 555],
         [ 21,  22,  23]],

        [[ 24,  25,  26],
         [555, 555, 555],
         [ 27,  28,  29]],

        [[ 30,  31,  32],
         [555, 555, 555],
         [ 33,  34,  35]]],


       [[[ 36,  37,  38],
         [555, 555, 555],
         [ 39,  40,  41]],

        [[ 42,  43,  44],
         [555, 555, 555],
         [ 45,  46,  47]],

        [[ 48,  49,  50],
         [555, 555, 555],
         [ 51,  52,  53]]],


       [[[ 54,  55,  56],
         [555, 555, 555],
         [ 57,  58,  59]],

        [[ 60,  61,  62],
         [555, 555, 555],
         [ 63,  64,  65]],

        [[ 66,  67,  68],
         [555, 555, 555],
         [ 69,  70,  71]]]])

In [83]:
np.insert(e,1,555,axis= 2)

array([[[[  0,   1,   2],
         [555, 555, 555],
         [  3,   4,   5]],

        [[  6,   7,   8],
         [555, 555, 555],
         [  9,  10,  11]],

        [[ 12,  13,  14],
         [555, 555, 555],
         [ 15,  16,  17]]],


       [[[ 18,  19,  20],
         [555, 555, 555],
         [ 21,  22,  23]],

        [[ 24,  25,  26],
         [555, 555, 555],
         [ 27,  28,  29]],

        [[ 30,  31,  32],
         [555, 555, 555],
         [ 33,  34,  35]]],


       [[[ 36,  37,  38],
         [555, 555, 555],
         [ 39,  40,  41]],

        [[ 42,  43,  44],
         [555, 555, 555],
         [ 45,  46,  47]],

        [[ 48,  49,  50],
         [555, 555, 555],
         [ 51,  52,  53]]],


       [[[ 54,  55,  56],
         [555, 555, 555],
         [ 57,  58,  59]],

        [[ 60,  61,  62],
         [555, 555, 555],
         [ 63,  64,  65]],

        [[ 66,  67,  68],
         [555, 555, 555],
         [ 69,  70,  71]]]])

In [86]:
np.insert(e,1,555,axis= -3)

array([[[[  0,   1,   2],
         [  3,   4,   5]],

        [[555, 555, 555],
         [555, 555, 555]],

        [[  6,   7,   8],
         [  9,  10,  11]],

        [[ 12,  13,  14],
         [ 15,  16,  17]]],


       [[[ 18,  19,  20],
         [ 21,  22,  23]],

        [[555, 555, 555],
         [555, 555, 555]],

        [[ 24,  25,  26],
         [ 27,  28,  29]],

        [[ 30,  31,  32],
         [ 33,  34,  35]]],


       [[[ 36,  37,  38],
         [ 39,  40,  41]],

        [[555, 555, 555],
         [555, 555, 555]],

        [[ 42,  43,  44],
         [ 45,  46,  47]],

        [[ 48,  49,  50],
         [ 51,  52,  53]]],


       [[[ 54,  55,  56],
         [ 57,  58,  59]],

        [[555, 555, 555],
         [555, 555, 555]],

        [[ 60,  61,  62],
         [ 63,  64,  65]],

        [[ 66,  67,  68],
         [ 69,  70,  71]]]])

In [87]:
np.insert(e,1,555,axis= 3)

array([[[[  0, 555,   1,   2],
         [  3, 555,   4,   5]],

        [[  6, 555,   7,   8],
         [  9, 555,  10,  11]],

        [[ 12, 555,  13,  14],
         [ 15, 555,  16,  17]]],


       [[[ 18, 555,  19,  20],
         [ 21, 555,  22,  23]],

        [[ 24, 555,  25,  26],
         [ 27, 555,  28,  29]],

        [[ 30, 555,  31,  32],
         [ 33, 555,  34,  35]]],


       [[[ 36, 555,  37,  38],
         [ 39, 555,  40,  41]],

        [[ 42, 555,  43,  44],
         [ 45, 555,  46,  47]],

        [[ 48, 555,  49,  50],
         [ 51, 555,  52,  53]]],


       [[[ 54, 555,  55,  56],
         [ 57, 555,  58,  59]],

        [[ 60, 555,  61,  62],
         [ 63, 555,  64,  65]],

        [[ 66, 555,  67,  68],
         [ 69, 555,  70,  71]]]])

In [85]:
np.insert(e,1,555,axis= -4)

array([[[[  0,   1,   2],
         [  3,   4,   5]],

        [[  6,   7,   8],
         [  9,  10,  11]],

        [[ 12,  13,  14],
         [ 15,  16,  17]]],


       [[[555, 555, 555],
         [555, 555, 555]],

        [[555, 555, 555],
         [555, 555, 555]],

        [[555, 555, 555],
         [555, 555, 555]]],


       [[[ 18,  19,  20],
         [ 21,  22,  23]],

        [[ 24,  25,  26],
         [ 27,  28,  29]],

        [[ 30,  31,  32],
         [ 33,  34,  35]]],


       [[[ 36,  37,  38],
         [ 39,  40,  41]],

        [[ 42,  43,  44],
         [ 45,  46,  47]],

        [[ 48,  49,  50],
         [ 51,  52,  53]]],


       [[[ 54,  55,  56],
         [ 57,  58,  59]],

        [[ 60,  61,  62],
         [ 63,  64,  65]],

        [[ 66,  67,  68],
         [ 69,  70,  71]]]])

In [96]:
np.insert(e,1,555,axis= -1)

array([[[[  0, 555,   1,   2],
         [  3, 555,   4,   5]],

        [[  6, 555,   7,   8],
         [  9, 555,  10,  11]],

        [[ 12, 555,  13,  14],
         [ 15, 555,  16,  17]]],


       [[[ 18, 555,  19,  20],
         [ 21, 555,  22,  23]],

        [[ 24, 555,  25,  26],
         [ 27, 555,  28,  29]],

        [[ 30, 555,  31,  32],
         [ 33, 555,  34,  35]]],


       [[[ 36, 555,  37,  38],
         [ 39, 555,  40,  41]],

        [[ 42, 555,  43,  44],
         [ 45, 555,  46,  47]],

        [[ 48, 555,  49,  50],
         [ 51, 555,  52,  53]]],


       [[[ 54, 555,  55,  56],
         [ 57, 555,  58,  59]],

        [[ 60, 555,  61,  62],
         [ 63, 555,  64,  65]],

        [[ 66, 555,  67,  68],
         [ 69, 555,  70,  71]]]])

In [93]:
np.insert(e,1,555,axis= 1)

array([[[[  0,   1,   2],
         [  3,   4,   5]],

        [[555, 555, 555],
         [555, 555, 555]],

        [[  6,   7,   8],
         [  9,  10,  11]],

        [[ 12,  13,  14],
         [ 15,  16,  17]]],


       [[[ 18,  19,  20],
         [ 21,  22,  23]],

        [[555, 555, 555],
         [555, 555, 555]],

        [[ 24,  25,  26],
         [ 27,  28,  29]],

        [[ 30,  31,  32],
         [ 33,  34,  35]]],


       [[[ 36,  37,  38],
         [ 39,  40,  41]],

        [[555, 555, 555],
         [555, 555, 555]],

        [[ 42,  43,  44],
         [ 45,  46,  47]],

        [[ 48,  49,  50],
         [ 51,  52,  53]]],


       [[[ 54,  55,  56],
         [ 57,  58,  59]],

        [[555, 555, 555],
         [555, 555, 555]],

        [[ 60,  61,  62],
         [ 63,  64,  65]],

        [[ 66,  67,  68],
         [ 69,  70,  71]]]])