In [1]:
import numpy as np

# input 1-D array 
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
np.array_split(a,6)

[array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10]),
 array([11, 12]),
 array([13, 14])]

In [5]:
# input 2-D array 
b = np.arange(30).reshape(6,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [6]:
np.array_split(b,[2,3])

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])]

In [8]:
np.array_split(b,3,axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23],
        [27, 28]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29]])]

In [15]:
# input 3-D array 
c = np.arange(30).reshape(2,3,5)
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [16]:
np.array_split(c,3,axis=1)

[array([[[ 0,  1,  2,  3,  4]],
 
        [[15, 16, 17, 18, 19]]]),
 array([[[ 5,  6,  7,  8,  9]],
 
        [[20, 21, 22, 23, 24]]]),
 array([[[10, 11, 12, 13, 14]],
 
        [[25, 26, 27, 28, 29]]])]

In [17]:
np.array_split(c,2,axis=0)

[array([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]]]),
 array([[[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])]

In [19]:
np.array_split(c,2,axis=2)

[array([[[ 0,  1,  2],
         [ 5,  6,  7],
         [10, 11, 12]],
 
        [[15, 16, 17],
         [20, 21, 22],
         [25, 26, 27]]]),
 array([[[ 3,  4],
         [ 8,  9],
         [13, 14]],
 
        [[18, 19],
         [23, 24],
         [28, 29]]])]

In [20]:
np.array_split(c,(2,1,1,1))

[array([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]],
 
        [[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]]),
 array([], shape=(0, 3, 5), dtype=int64),
 array([], shape=(0, 3, 5), dtype=int64),
 array([], shape=(0, 3, 5), dtype=int64),
 array([[[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])]