In [14]:
import numpy as np

# input 3-D array 
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
#split with section
np.dsplit(a,2)

[array([[[ 0,  1],
         [ 4,  5],
         [ 8,  9]],
 
        [[12, 13],
         [16, 17],
         [20, 21]]]),
 array([[[ 2,  3],
         [ 6,  7],
         [10, 11]],
 
        [[14, 15],
         [18, 19],
         [22, 23]]])]

In [16]:
#split with indecies
np.dsplit(a,[1,2])

[array([[[ 0],
         [ 4],
         [ 8]],
 
        [[12],
         [16],
         [20]]]),
 array([[[ 1],
         [ 5],
         [ 9]],
 
        [[13],
         [17],
         [21]]]),
 array([[[ 2,  3],
         [ 6,  7],
         [10, 11]],
 
        [[14, 15],
         [18, 19],
         [22, 23]]])]