In [3]:
import numpy as np

# input 2-D array 
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
#horizontal split ==> column wise
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [5]:
#split based on indicies
np.hsplit(a,(1,3))

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [30]:
# input 3-D array
b = np.array([[[13,14,15,0],[16,17,18,1],[0,1,2,4]],[[19,20,21,2],[22,23,24,3],[5,6,7,8]],[[25,26,27,4],[28,29,30,5],[9,10,11,12]],[[31,32,33,6],[34,35,36,7],[13,14,15,16]]])
b.shape

(4, 3, 4)

In [32]:
np.hsplit(b,1)

[array([[[13, 14, 15,  0],
         [16, 17, 18,  1],
         [ 0,  1,  2,  4]],
 
        [[19, 20, 21,  2],
         [22, 23, 24,  3],
         [ 5,  6,  7,  8]],
 
        [[25, 26, 27,  4],
         [28, 29, 30,  5],
         [ 9, 10, 11, 12]],
 
        [[31, 32, 33,  6],
         [34, 35, 36,  7],
         [13, 14, 15, 16]]])]

In [33]:
#split based on indicies
np.hsplit(b,(1,2))

[array([[[13, 14, 15,  0]],
 
        [[19, 20, 21,  2]],
 
        [[25, 26, 27,  4]],
 
        [[31, 32, 33,  6]]]),
 array([[[16, 17, 18,  1]],
 
        [[22, 23, 24,  3]],
 
        [[28, 29, 30,  5]],
 
        [[34, 35, 36,  7]]]),
 array([[[ 0,  1,  2,  4]],
 
        [[ 5,  6,  7,  8]],
 
        [[ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16]]])]