In [1]:
import numpy as np

#input 1-D array
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
#output==> splitted into 5 parts
np.split(a,5)

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15]),
 array([16, 17, 18, 19])]

In [17]:
# input 2-D array 
b = np.arange(20).reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [18]:
#output==> splitted into 2 parts
np.split(b,2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [19]:
#output==> split row wise with axis=0
np.split(b,2,axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [20]:
# input 2-D array 
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
#output==> split column wise with axis=1
np.split(c,2,axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [28]:
## splitting based on indicies
# for 1-D array
np.split(a,[4,9])

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]

In [29]:
# for 1-D array
np.split(a,[4,9,16])

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19])]

In [30]:
# for 1-D array
np.split(a,[4,9,13,17])

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7, 8]),
 array([ 9, 10, 11, 12]),
 array([13, 14, 15, 16]),
 array([17, 18, 19])]