In [32]:
import numpy as np

#input 1-D array
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
#output==> splitted into 5 parts
np.split(a,5)

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15]),
 array([16, 17, 18, 19])]

In [34]:
# input 2-D array 
b = np.arange(20).reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
#output==> splitted into 2 parts
np.split(b,2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [36]:
#output==> split row wise with axis=0
np.split(b,2,axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [37]:
# input 2-D array 
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
#output==> split column wise with axis=1
np.split(c,2,axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [39]:
## splitting based on indicies
# for 1-D array
np.split(a,[4,9])

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]

In [40]:
# for 1-D array
np.split(a,[4,9,16])

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19])]

In [44]:
# for 1-D array
np.split(a,[4,9,13,17])

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7, 8]),
 array([ 9, 10, 11, 12]),
 array([13, 14, 15, 16]),
 array([17, 18, 19])]

In [47]:
# splitting 2-D array based on indicies, axis=0

np.split(b,[1,2],axis=0)

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [48]:
np.split(b,[0,1,3],axis=0)

[array([], shape=(0, 5), dtype=int64),
 array([[0, 1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]])]

In [49]:
# splitting 2-D array based on indicies, axis=1
np.split(b,[1,2],axis=1)

[array([[ 0],
        [ 5],
        [10],
        [15]]),
 array([[ 1],
        [ 6],
        [11],
        [16]]),
 array([[ 2,  3,  4],
        [ 7,  8,  9],
        [12, 13, 14],
        [17, 18, 19]])]

In [54]:
np.split(b,[1,3,4],axis=1)

[array([[ 0],
        [ 5],
        [10],
        [15]]),
 array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17]]),
 array([[ 3],
        [ 8],
        [13],
        [18]]),
 array([[ 4],
        [ 9],
        [14],
        [19]])]

In [55]:
np.split(b,[1,3,3],axis=1)

[array([[ 0],
        [ 5],
        [10],
        [15]]),
 array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17]]),
 array([], shape=(4, 0), dtype=int64),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19]])]

In [56]:
np.split(b,[0,4],axis=1)

[array([], shape=(4, 0), dtype=int64),
 array([[ 0,  1,  2,  3],
        [ 5,  6,  7,  8],
        [10, 11, 12, 13],
        [15, 16, 17, 18]]),
 array([[ 4],
        [ 9],
        [14],
        [19]])]

In [57]:
np.split(b,[1,5,3],axis=1)

[array([[ 0],
        [ 5],
        [10],
        [15]]),
 array([[ 1,  2,  3,  4],
        [ 6,  7,  8,  9],
        [11, 12, 13, 14],
        [16, 17, 18, 19]]),
 array([], shape=(4, 0), dtype=int64),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19]])]

In [61]:
# input 3-D array
f = np.array([[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]],[[25,26,27],[28,29,30]],[[31,32,33],[34,35,36]]])
f

array([[[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30]],

       [[31, 32, 33],
        [34, 35, 36]]])

In [63]:
np.split(f,[1,3],axis=0)

[array([[[13, 14, 15],
         [16, 17, 18]]]),
 array([[[19, 20, 21],
         [22, 23, 24]],
 
        [[25, 26, 27],
         [28, 29, 30]]]),
 array([[[31, 32, 33],
         [34, 35, 36]]])]

In [65]:
np.split(f,[1,2],axis=1)

[array([[[13, 14, 15]],
 
        [[19, 20, 21]],
 
        [[25, 26, 27]],
 
        [[31, 32, 33]]]),
 array([[[16, 17, 18]],
 
        [[22, 23, 24]],
 
        [[28, 29, 30]],
 
        [[34, 35, 36]]]),
 array([], shape=(4, 0, 3), dtype=int64)]