In [3]:
import numpy as np

# input 2-D array 
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
#Vertical split ==> row wise
np.vsplit(a,2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [6]:
#split based on indicies
np.vsplit(a,(1,3))

[array([[0, 1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]])]

In [7]:
b = np.array([[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]],[[25,26,27],[28,29,30]],[[31,32,33],[34,35,36]],[[37,38,39],[40,41,42]],[[43,44,45],[46,47,48]]])
b.shape

(6, 2, 3)

In [8]:
#split based on indicies
np.vsplit(b,(1,2))

[array([[[13, 14, 15],
         [16, 17, 18]]]),
 array([[[19, 20, 21],
         [22, 23, 24]]]),
 array([[[25, 26, 27],
         [28, 29, 30]],
 
        [[31, 32, 33],
         [34, 35, 36]],
 
        [[37, 38, 39],
         [40, 41, 42]],
 
        [[43, 44, 45],
         [46, 47, 48]]])]