In [6]:
import numpy as np

# joining always based on axis=1, horizontal===> column wise

#input 1-D array
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
#input 1-D array
b = np.arange(21,41)
b

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40])

In [8]:
#output 1-D array
np.hstack((a,b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [9]:
# input 2-D array
c = np.arange(21,41).reshape(4,5)
c

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [10]:
# input 2-D array 
d = np.arange(20).reshape(4,5)
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
#output 2-D array
np.hstack((c,d))

array([[21, 22, 23, 24, 25,  0,  1,  2,  3,  4],
       [26, 27, 28, 29, 30,  5,  6,  7,  8,  9],
       [31, 32, 33, 34, 35, 10, 11, 12, 13, 14],
       [36, 37, 38, 39, 40, 15, 16, 17, 18, 19]])

In [15]:
# input 3-D array
e = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
e

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
# input 3-D array
f = np.array([[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]])
f

array([[[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [17]:
#output 3-D array
np.hstack((e,f))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [13, 14, 15],
        [16, 17, 18]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [19, 20, 21],
        [22, 23, 24]]])