In [1]:
import numpy as np

a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [54]:
b = np.arange(21,41)
b

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40])

In [64]:
np.stack((a,b))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40]])

In [61]:
c = np.arange(20).reshape(4,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [62]:
d = np.arange(21,41).reshape(4,5)
d

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [58]:
# stack input 2-D array and output 3-D array
np.stack((c,d), axis=0)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]]])

In [59]:
# stack input 2-D array and output 3-D array
np.stack((c,d), axis=1)

array([[[ 0,  1,  2,  3,  4],
        [21, 22, 23, 24, 25]],

       [[ 5,  6,  7,  8,  9],
        [26, 27, 28, 29, 30]],

       [[10, 11, 12, 13, 14],
        [31, 32, 33, 34, 35]],

       [[15, 16, 17, 18, 19],
        [36, 37, 38, 39, 40]]])

In [60]:
np.stack((c,d), axis=2)

array([[[ 0, 21],
        [ 1, 22],
        [ 2, 23],
        [ 3, 24],
        [ 4, 25]],

       [[ 5, 26],
        [ 6, 27],
        [ 7, 28],
        [ 8, 29],
        [ 9, 30]],

       [[10, 31],
        [11, 32],
        [12, 33],
        [13, 34],
        [14, 35]],

       [[15, 36],
        [16, 37],
        [17, 38],
        [18, 39],
        [19, 40]]])

In [44]:
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
e = np.array([[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]])
e

array([[[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [50]:
# stack input 3-D array and output 4-D array
np.stack((d,e), axis=0)

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]])

In [47]:
# stack input 3-D array and output 4-D array
np.stack((d,e), axis=1)

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[13, 14, 15],
         [16, 17, 18]]],


       [[[ 7,  8,  9],
         [10, 11, 12]],

        [[19, 20, 21],
         [22, 23, 24]]]])

In [48]:
np.stack((d,e), axis=2)

array([[[[ 1,  2,  3],
         [13, 14, 15]],

        [[ 4,  5,  6],
         [16, 17, 18]]],


       [[[ 7,  8,  9],
         [19, 20, 21]],

        [[10, 11, 12],
         [22, 23, 24]]]])

In [51]:
np.stack((d,e), axis=3)

array([[[[ 1, 13],
         [ 2, 14],
         [ 3, 15]],

        [[ 4, 16],
         [ 5, 17],
         [ 6, 18]]],


       [[[ 7, 19],
         [ 8, 20],
         [ 9, 21]],

        [[10, 22],
         [11, 23],
         [12, 24]]]])