In [1]:
import numpy as np


In [27]:
#creating ndarray 1-D array
arr = np.arange(1,200,3)
arr

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100, 103, 106, 109, 112, 115,
       118, 121, 124, 127, 130, 133, 136, 139, 142, 145, 148, 151, 154,
       157, 160, 163, 166, 169, 172, 175, 178, 181, 184, 187, 190, 193,
       196, 199])

In [29]:
#by creating new ndarray by passing index of data needed i.e. 7,22,61,136,181
i = np.array([2,7,20,45,60])
arr[i]

array([  7,  22,  61, 136, 181])

In [31]:
# or directly passing indexes as argument to the original array
arr[[2,7,20,45,60]]

array([  7,  22,  61, 136, 181])

In [33]:
# creating 2-D array
t = np.random.randn(2,3)
t

array([[ 0.17268045, -0.8935125 ,  0.47587304],
       [ 0.39950321,  1.42786261, -0.08994672]])

In [37]:
# by directly passing indexes as argument to the original array
t[[0,1],[1,2]] 

array([-0.8935125 , -0.08994672])

In [39]:
#Accessing elements from 3-D array
b = np.random.randn(2,3,4)
b

array([[[ 0.87737952,  1.11926501,  1.63223317,  0.5640337 ],
        [ 0.01946757, -0.72093901, -1.0220187 ,  0.12252158],
        [-1.47058446,  1.77945125,  0.63705683, -1.22796716]],

       [[ 2.09734417,  1.29664154, -0.08079681, -1.00950271],
        [-1.05896506, -0.94271389,  0.79851406, -0.51995955],
        [-1.34783238,  0.47796944,  0.69976415, -0.44696956]]])

In [43]:
# by directly passing indexes as argument to the original array
b[[0,1],[0,1],[1,2]] 

array([1.11926501, 0.79851406])