In [1]:
import numpy as np

#Slicing of 1-D array
a= np.array([10,20,30,40,50,60,70])
a

array([10, 20, 30, 40, 50, 60, 70])

In [2]:
#slicing from 1 index to 3 index
a[1:4]

array([20, 30, 40])

In [4]:
#slicing from -4 index to -1 index
a[-4:-1]

array([40, 50, 60])

In [6]:
#slicing from 0 index to -3 index
a[:-3]

array([10, 20, 30, 40])

In [7]:
#slicing from 0 index to last index
a[:]

array([10, 20, 30, 40, 50, 60, 70])

In [8]:
#slicing from 2 index to last index
a[2:]

array([30, 40, 50, 60, 70])

In [9]:
#slicing from 2 index to last index with step 2
a[2::2]

array([30, 50, 70])

In [11]:
#slicing from -4 index to -1 index with step 2
a[-4:-1:2]

array([40, 60])

In [ ]:
#slicing from 0 index to last index with step 3
a[::3]

In [17]:
#creating 2-D array
b= np.array([[10,20,30],[40,50,60],[70,80,90],[100,101,102]])
b

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 101, 102]])

In [18]:
#slicing from row(1 index to 3-1 index) column(0 index to 1-1 index)
b[1:3,0:1]

array([[40],
       [70]])

In [19]:
#Slicing all index
b[::, ::]

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 101, 102]])

In [20]:
#slicing from row(1 index to last index with step 2) column(0 index to 2-1 index with step 2)
b[1::2,0:2]

array([[ 40,  50],
       [100, 101]])

In [21]:
b[-3:-1:2, -2:-1]

array([[50]])