In [1]:
import numpy as np

a = np.array([5,3,6,8,10])
a

array([ 5,  3,  6,  8, 10])

In [2]:
# by default in ascending order
np.sort(a)

array([ 3,  5,  6,  8, 10])

In [3]:
# first way: for decending order
np.sort(a)[::-1]

array([10,  8,  6,  5,  3])

In [4]:
#second way:  for decending order
-np.sort(-a)

array([10,  8,  6,  5,  3])