In [1]:
import numpy as np

#Sorting for 1-D arrays
a = np.array([5,3,6,8,10])
a

array([ 5,  3,  6,  8, 10])

In [2]:
# by default in ascending order
np.sort(a)

array([ 3,  5,  6,  8, 10])

In [3]:
# first way: for decending order
np.sort(a)[::-1]

array([10,  8,  6,  5,  3])

In [4]:
#second way:  for decending order
-np.sort(-a)

array([10,  8,  6,  5,  3])

In [6]:
# sort string
b = np.array(['cat','rat','cup','clap','fun'])
b

array(['cat', 'rat', 'cup', 'clap', 'fun'], dtype='<U4')

In [7]:
# sort in ascending order
np.sort(b)

array(['cat', 'clap', 'cup', 'fun', 'rat'], dtype='<U4')

In [8]:
# first way: for decending order
np.sort(b)[::-1]

array(['rat', 'fun', 'cup', 'clap', 'cat'], dtype='<U4')

In [10]:
#Sorting for 2-D arrays
c = np.array([[13, 2, 3, 54], [15, 26, 17, 8], [39, 12, 78, 10]])
c

array([[13,  2,  3, 54],
       [15, 26, 17,  8],
       [39, 12, 78, 10]])

In [11]:
# sort in ascending order, columns get sorted
np.sort(c)

array([[ 2,  3, 13, 54],
       [ 8, 15, 17, 26],
       [10, 12, 39, 78]])

In [12]:
# sort in ascending order, row get sorted
np.sort(c, axis=0)

array([[13,  2,  3,  8],
       [15, 12, 17, 10],
       [39, 26, 78, 54]])

In [13]:
# sort in ascending order, column get sorted
np.sort(c, axis=1)

array([[ 2,  3, 13, 54],
       [ 8, 15, 17, 26],
       [10, 12, 39, 78]])

In [14]:
# sort in ascending order, row get sorted
np.sort(c, axis=-2)

array([[13,  2,  3,  8],
       [15, 12, 17, 10],
       [39, 26, 78, 54]])

In [15]:
# sort in descending order, column get sorted
np.sort(c, axis=1)[::-1]

array([[10, 12, 39, 78],
       [ 8, 15, 17, 26],
       [ 2,  3, 13, 54]])

In [16]:
# sort in descending order, row get sorted
np.sort(c, axis=0)[::-1]

array([[39, 26, 78, 54],
       [15, 12, 17, 10],
       [13,  2,  3,  8]])

In [23]:
#sort for 1-D arrays dtype = object but doesn't support sorting between int and string dtype will throw error.
e = np.array([5,3.2,6,8,10,16.8,9,18,4.5,True,False,0],dtype='object')
e

array([5, 3.2, 6, 8, 10, 16.8, 9, 18, 4.5, True, False, 0], dtype=object)

In [20]:
np.sort(e)

array([False, 0, True, 3.2, 4.5, 5, 6, 8, 9, 10, 16.8, 18], dtype=object)