In [1]:
import numpy as np

#creating ones 1-d array
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [2]:
#creating ones 2-d array
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
#creating ones 3-d array
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])