In [4]:
import numpy as np

#creating array using full() with shape(3,3) & value should be 5
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [5]:
#creating 1-d array with value 7
np.full((3,),7)

array([7, 7, 7])

In [6]:
#creating 3-d array with value 6
np.full((2,3,5),6)

array([[[6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6]],

       [[6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6]]])

In [8]:
np.full((2,3,5),6).size

30

In [9]:
#creating 4-d array with value 8
np.full((3,5,7),6)

array([[[6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6]],

       [[6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6]],

       [[6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6]]])

In [11]:
np.full((3,5,7),6).size

105