In [1]:
import numpy as np

#creating eye() array with value N and M
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [2]:
#creating eye() array with only value N, by default M value should be same as M
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [3]:
# creating array with dtype
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [4]:
np.eye(2,3, dtype= int)

array([[1, 0, 0],
       [0, 1, 0]])

In [8]:
#creating eye() array with value N,M, dtype and k=0
np.eye(4,4,0, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [10]:
#creating eye() array with value N,M, dtype and k=1
np.eye(4,4,1, dtype=int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [11]:
#creating eye() array with value N,M, dtype and k=-1
np.eye(4,4,-1, dtype=int)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [12]:
#creating eye() array with value N,M, dtype and k=-2
np.eye(4,4,-2, dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

In [13]:
#creating eye() array with value N,M, dtype and k=-2, order = 'F'
np.eye(4,4,-2, dtype=int, order ='F')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])