In [1]:
import numpy as np

a = np.array([[10,20,30],[40,50,60]])
b = np.array([[70,80,90],[100,101,102]])

In [3]:
# addition
np.add(a,b)

array([[ 80, 100, 120],
       [140, 151, 162]])

In [4]:
# substarction
np.subtract(a,b)

array([[-60, -60, -60],
       [-60, -51, -42]])

In [5]:
# multiply
np.multiply(a,b)

array([[ 700, 1600, 2700],
       [4000, 5050, 6120]])

In [6]:
# divide
np.divide(a,b)

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.4950495 , 0.58823529]])

In [7]:
# floor divide
np.floor_divide(a,b)

array([[0, 0, 0],
       [0, 0, 0]])

In [8]:
# modulo
np.mod(a,b)

array([[10, 20, 30],
       [40, 50, 60]])

In [9]:
# Power or Exponential 
np.power(a,b)

array([[0, 0, 0],
       [0, 0, 0]])