In [16]:
import numpy as np

a = np.array([[10,20,30],[40,50,60]])
b = np.array([10,20,30])

In [17]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [18]:
b

array([10, 20, 30])

In [19]:
a.shape

(2, 3)

In [20]:
b.shape

(3,)

In [21]:
a.ndim

2

In [22]:
b.ndim

1

In [23]:
a.size

6

In [25]:
b.size

3

In [26]:
#bradcasting addition
a+b

array([[20, 40, 60],
       [50, 70, 90]])

In [29]:
t = np.array([[10],[20],[30]])
s = np.array([10,20,30])

In [30]:
#bradcasting substraction
t-s

array([[  0, -10, -20],
       [ 10,   0, -10],
       [ 20,  10,   0]])

In [31]:
#bradcasting addition
t+s

array([[20, 30, 40],
       [30, 40, 50],
       [40, 50, 60]])

In [32]:
#bradcasting floor_division
t//s

array([[1, 0, 0],
       [2, 1, 0],
       [3, 1, 1]])