In [1]:
import numpy as np
 
#For 1-D arrays
a = np.array([5,3.2,6,8,10,16.8,9,18,4.5,True,'Hello',False,0],dtype='object')
a

array([5, 3.2, 6, 8, 10, 16.8, 9, 18, 4.5, True, 'Hello', False, 0],
      dtype=object)

In [2]:
#delete value at index = 10
np.delete(a,10)

array([5, 3.2, 6, 8, 10, 16.8, 9, 18, 4.5, True, False, 0], dtype=object)

In [3]:
# delete value at index = [1,3,6]
np.delete(a,[1,3,6])

array([5, 6, 10, 16.8, 18, 4.5, True, 'Hello', False, 0], dtype=object)

In [5]:
# delete element from 2 to 7 using slice
np.delete(a,np.s_[2:7])

array([5, 3.2, 18, 4.5, True, 'Hello', False, 0], dtype=object)

In [7]:
# delete all the elements
np.delete(a,np.s_[:])

array([], dtype=object)

In [11]:
np.delete(a,range(2,6))

array([5, 3.2, 9, 18, 4.5, True, 'Hello', False, 0], dtype=object)

In [12]:
# 2-D arrays
b = np.array([[13, 2, 3, 54], [15, 26, 17, 8], [39, 12, 78, 10]])
b

array([[13,  2,  3, 54],
       [15, 26, 17,  8],
       [39, 12, 78, 10]])

In [13]:
# if axis not provided then 2-D arrary convert into 1-D array and the delete
np.delete(b,3)

array([13,  2,  3, 15, 26, 17,  8, 39, 12, 78, 10])

In [15]:
#delete axis=0
np.delete(b,1,axis=0)

array([[13,  2,  3, 54],
       [39, 12, 78, 10]])

In [16]:
#delete axis=1
np.delete(b,1,axis=1)

array([[13,  3, 54],
       [15, 17,  8],
       [39, 78, 10]])

In [18]:
#delete axis=0
np.delete(b,[0,2],axis=0)

array([[15, 26, 17,  8]])

In [20]:
#delete axis=1
np.delete(b,[0,2],axis=1)

array([[ 2, 54],
       [26,  8],
       [12, 10]])

In [21]:
# 3-D arrays
c = np.array([[[13, 2, 3, 54], [15, 26, 17, 8]], [[39, 12, 78, 10],[0, 1, 16, 77]]])
c

array([[[13,  2,  3, 54],
        [15, 26, 17,  8]],

       [[39, 12, 78, 10],
        [ 0,  1, 16, 77]]])

In [22]:
#delete with axis=None
np.delete(c,5)

array([13,  2,  3, 54, 15, 17,  8, 39, 12, 78, 10,  0,  1, 16, 77])

In [24]:
#delete axis=0
np.delete(c,1,axis=0)

array([[[13,  2,  3, 54],
        [15, 26, 17,  8]]])

In [25]:
#delete axis=1
np.delete(c,1,axis=1)

array([[[13,  2,  3, 54]],

       [[39, 12, 78, 10]]])

In [26]:
#delete axis=2
np.delete(c,1,axis=2)

array([[[13,  3, 54],
        [15, 17,  8]],

       [[39, 78, 10],
        [ 0, 16, 77]]])