In [6]:
from numpy import random as rn


In [10]:
#generate single random array between 30 and 60
rn.randint(30,60)

44

In [14]:
# create 1-D array with size 4
rn.randint(30,60,size = 4)

array([46, 32, 55, 53])

In [15]:
# create 1-D array with size 30
rn.randint(30,60,30)

array([53, 34, 33, 36, 53, 34, 37, 45, 45, 52, 50, 54, 37, 32, 41, 36, 51,
       51, 33, 33, 32, 34, 35, 43, 49, 34, 55, 50, 58, 35])

In [16]:
# create 1-D array with size 100
rn.randint(30,60,100)

array([46, 32, 46, 36, 31, 37, 49, 45, 42, 58, 47, 57, 52, 54, 44, 56, 43,
       57, 41, 35, 34, 37, 54, 38, 56, 50, 42, 58, 50, 54, 36, 37, 45, 59,
       33, 39, 44, 34, 59, 39, 41, 34, 36, 33, 30, 31, 37, 59, 47, 51, 40,
       57, 45, 30, 45, 46, 40, 59, 56, 54, 48, 35, 53, 57, 53, 43, 55, 44,
       39, 39, 48, 52, 38, 34, 34, 38, 36, 58, 39, 46, 51, 57, 30, 41, 32,
       51, 47, 58, 32, 54, 35, 52, 44, 32, 55, 44, 30, 48, 43, 45])