In [2]:
from numpy import random as rn

#passing no parameter
rn.uniform()

0.10244022109411832

In [4]:
#passing single value
rn.uniform(10)

4.132259062098738

In [5]:
#range in between 2 to 3
rn.uniform(2,3)

2.2575507373163974

In [6]:
#creating 1-D array
rn.uniform(2,3, size=(2,3))

array([[2.18473153, 2.32091893, 2.1466388 ],
       [2.16634099, 2.79607946, 2.6746047 ]])

In [8]:
#creating 1-D array
rn.uniform(2,3, size=(5))

array([2.91256638, 2.29039788, 2.33603763, 2.04490598, 2.47003972])

In [9]:
#creating 2-D array
rn.uniform(2,3, size=(2,2,3))

array([[[2.65093951, 2.31047744, 2.55213876],
        [2.95527906, 2.16881071, 2.57879687]],

       [[2.31588456, 2.08430815, 2.39685189],
        [2.20021767, 2.26158991, 2.42232194]]])