In [6]:
from numpy import random as rn


In [10]:
#generate single random array between 30 and 60
rn.randint(30,60)

44

In [14]:
# create 1-D array with size 4
rn.randint(30,60,size = 4)

array([46, 32, 55, 53])

In [15]:
# create 1-D array with size 30
rn.randint(30,60,30)

array([53, 34, 33, 36, 53, 34, 37, 45, 45, 52, 50, 54, 37, 32, 41, 36, 51,
       51, 33, 33, 32, 34, 35, 43, 49, 34, 55, 50, 58, 35])

In [16]:
# create 1-D array with size 100
rn.randint(30,60,100)

array([46, 32, 46, 36, 31, 37, 49, 45, 42, 58, 47, 57, 52, 54, 44, 56, 43,
       57, 41, 35, 34, 37, 54, 38, 56, 50, 42, 58, 50, 54, 36, 37, 45, 59,
       33, 39, 44, 34, 59, 39, 41, 34, 36, 33, 30, 31, 37, 59, 47, 51, 40,
       57, 45, 30, 45, 46, 40, 59, 56, 54, 48, 35, 53, 57, 53, 43, 55, 44,
       39, 39, 48, 52, 38, 34, 34, 38, 36, 58, 39, 46, 51, 57, 30, 41, 32,
       51, 47, 58, 32, 54, 35, 52, 44, 32, 55, 44, 30, 48, 43, 45])

In [18]:
#Creating a 2-D array in a from 0 to 50 with size(3,4)
rn.randint(50,size=(3,4))

array([[ 3, 38, 15, 40],
       [12, 36,  3, 11],
       [45, 48, 30, 38]])

In [22]:
#Creating a 3-D array in a from 0 to 50 with size(3,4,5)
rn.randint(50,size=(3,4,5))

array([[[11, 23, 39, 21, 34],
        [32, 20, 34, 21, 29],
        [16, 21, 20, 11, 43],
        [ 6, 49, 47, 33, 14]],

       [[20, 19, 37, 16, 23],
        [ 9, 17,  1, 15,  1],
        [24,  2, 23, 12, 21],
        [35, 42, 33, 48, 15]],

       [[23, 41, 39, 16, 10],
        [38, 24, 45, 26, 24],
        [34, 38, 40, 46,  0],
        [46, 12,  9, 43, 19]]])

In [26]:
#check default dtype of nd array
arr= rn.randint(10,size=(4,5))
arr

array([[4, 2, 2, 1, 5],
       [7, 5, 3, 9, 8],
       [8, 5, 1, 9, 4],
       [0, 0, 0, 3, 7]])

In [27]:
type(arr)

numpy.ndarray

In [28]:
arr.dtype

dtype('int64')

In [35]:
#creating new dtype='int8' of nd array
newarr= rn.randint(10,size=(4,5), dtype='int8')
newarr

array([[1, 1, 2, 3, 7],
       [3, 8, 0, 8, 4],
       [8, 1, 0, 5, 8],
       [4, 2, 6, 5, 1]], dtype=int8)

In [33]:
#checking the memory utilization size of both ndarray with different dtype 

import sys

sys.getsizeof(arr)

288

In [34]:
sys.getsizeof(newarr)

148

In [36]:
#converting int nd array to float

arr.astype(float)

array([[4., 2., 2., 1., 5.],
       [7., 5., 3., 9., 8.],
       [8., 5., 1., 9., 4.],
       [0., 0., 0., 3., 7.]])

In [37]:
sys.getsizeof(arr.astype(float))

288