In [19]:
import numpy
from numpy import random as rn

a= numpy.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
#shuffle-- the array modify the sequence of inline elements in different order

rn.shuffle(a)
a

array([ 1, 11,  8,  3,  6, 19, 17, 14,  2,  7,  9,  0, 16, 10, 15, 12, 18,
        5, 13,  4])

In [28]:
b=rn.randint(10,20,size=(3,4))
b

array([[19, 19, 11, 17],
       [15, 17, 18, 17],
       [18, 15, 11, 10]])

In [31]:
# shuffle 2-D array - only row order changed but internal element order remain same.
rn.shuffle(b)
b

array([[18, 15, 11, 10],
       [15, 17, 18, 17],
       [19, 19, 11, 17]])

In [34]:
c=rn.randint(10,20,size=(8,6))
c

array([[10, 10, 18, 12, 14, 11],
       [12, 10, 16, 10, 17, 17],
       [17, 15, 18, 14, 10, 14],
       [11, 14, 15, 15, 11, 17],
       [17, 11, 15, 13, 11, 12],
       [10, 12, 18, 18, 16, 15],
       [13, 14, 13, 13, 18, 15],
       [11, 14, 12, 11, 11, 11]])

In [35]:
# only row order changed but internal element order remain same.
rn.shuffle(c)
c

array([[11, 14, 15, 15, 11, 17],
       [11, 14, 12, 11, 11, 11],
       [10, 12, 18, 18, 16, 15],
       [13, 14, 13, 13, 18, 15],
       [10, 10, 18, 12, 14, 11],
       [17, 11, 15, 13, 11, 12],
       [12, 10, 16, 10, 17, 17],
       [17, 15, 18, 14, 10, 14]])