In [1]:
import numpy as np
from numpy import linalg as la

a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
la.det(a)

-2.0000000000000004

In [17]:
# 3x3 matrix
b = np.array([[1,2,4],[3,4,5],[7,8,9]])
b

array([[1, 2, 4],
       [3, 4, 5],
       [7, 8, 9]])

In [15]:
la.det(b)

-4.000000000000003

In [19]:
#3-D array
c = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [21]:
la.det(c)

array([-9.51619735e-16, -9.51619735e-16])