In [5]:
import numpy as np
from numpy import linalg as la

a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
# Array/Matrix Inverse of 2-D array
la.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [23]:
# Array/Matrix Inverse of 3-D array
b = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [21]:
la.inv(b)

array([[[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
        [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
        [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]],

       [[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
        [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
        [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]]])