In [1]:
import numpy as np
from numpy import linalg as la

a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [5]:
#power is zero (Identity matrix)
la.matrix_power(a,0)

array([[1, 0],
       [0, 1]])

In [7]:
#power greater than zero (normal power operation)
la.matrix_power(a,2)

array([[ 7, 10],
       [15, 22]])

In [9]:
la.matrix_power(a,8)

array([[165751, 241570],
       [362355, 528106]])

In [11]:
#power less than zero (first inverse then power operation is performed)
la.matrix_power(a,-2)

array([[ 5.5 , -2.5 ],
       [-3.75,  1.75]])

In [13]:
la.matrix_power(a,-8)

array([[ 2062.9140625 ,  -943.6328125 ],
       [-1415.44921875,   647.46484375]])

In [15]:
#3-D array
b = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [17]:
#power is zero for Identity for 3-D array
la.matrix_power(b,0)

array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]])

In [19]:
#power less than zero for 3-D array
la.matrix_power(b,-8)

array([[[ 2.73099729e+129, -5.46199458e+129,  2.73099729e+129],
        [-5.46199458e+129,  1.09239892e+130, -5.46199458e+129],
        [ 2.73099729e+129, -5.46199458e+129,  2.73099729e+129]],

       [[ 2.73099729e+129, -5.46199458e+129,  2.73099729e+129],
        [-5.46199458e+129,  1.09239892e+130, -5.46199458e+129],
        [ 2.73099729e+129, -5.46199458e+129,  2.73099729e+129]]])

In [21]:
#power greater than zero for 3-D array
la.matrix_power(b,8)

array([[[  510008400,   626654232,   743300064],
        [ 1154967822,  1419124617,  1683281412],
        [ 1799927244, -2083372294, -1671704536]],

       [[  510008400,   626654232,   743300064],
        [ 1154967822,  1419124617,  1683281412],
        [ 1799927244, -2083372294, -1671704536]]])