In [41]:
import numpy as np

#creating 2-d array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [51]:
# saving this above multiple arrays into file- "SavezTestFile.npz" using savez(), 
#override data, only single object of file created.
#extension npz
filename = 'SavezTestFile.npz'
np.savez(filename,a,b)

In [55]:
# return npz file object
fileObject = np.load(filename)
fileObject

NpzFile 'SavezTestFile.npz' with keys: arr_0, arr_1

In [83]:
#to get names of stored objects in file
fileObject.files

['arr_0', 'arr_1']

In [85]:
# to call the array at 0 position
fileObject['arr_0']

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
# to call the array at 1 position
fileObject['arr_1']

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])