In [3]:
import numpy as np

#for 1-D array
a = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [5]:
np.sum(a)

150

In [10]:
a.sum()

150

In [12]:
#for 2-D array
b = np.array([[100,1,600],[400,500,300],[700,200,900],[800,9,20]])
b

array([[100,   1, 600],
       [400, 500, 300],
       [700, 200, 900],
       [800,   9,  20]])

In [14]:
# without axis
np.sum(b)

4530

In [16]:
# with axis = 0 (row vise)
np.sum(b, axis=0)

array([2000,  710, 1820])

In [18]:
# with axis = 1 (column vise)
np.sum(b, axis=1)

array([ 701, 1200, 1800,  829])