In [1]:
import numpy as np

#for 1-D array
a = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [5]:
# mean or average value
np.mean(a)

30.0

In [7]:
# mean value with datatype
np.mean(a, dtype= int)

30

In [12]:
a.mean()

30.0

In [14]:
#for 2-D array
b = np.array([[100,1,600],[400,500,300],[700,200,900],[800,9,20]])
b

array([[100,   1, 600],
       [400, 500, 300],
       [700, 200, 900],
       [800,   9,  20]])

In [16]:
# without axis
np.mean(b)

377.5

In [18]:
# with axis = 0 (row vise)
np.mean(b, axis=0)

array([500. , 177.5, 455. ])

In [22]:
# with axis = 1 (column vise) and dtype
np.mean(b, axis=1, dtype=int)

array([233, 400, 600, 276])