In [45]:
import numpy as np

#for 1-D array
a = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [15]:
np.min(a)

10

In [17]:
np.amin(a)

10

In [19]:
a.min()

10

In [63]:
#for 2-D array
b = np.array([[100,1,600],[400,500,300],[700,200,900],[800,9,20]])
b

array([[100,   1, 600],
       [400, 500, 300],
       [700, 200, 900],
       [800,   9,  20]])

In [65]:
#without giving axis
np.amin(b)

1

In [67]:
#with axis = 0 (row vise)
np.amin(b, axis=0)

array([100,   1,  20])

In [69]:
#with axis = 1 (column vise)
np.amin(b,axis=1)

array([  1, 300, 200,   9])