In [1]:
import numpy as np

#for 1-D array
a = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [3]:
np.var(a)

200.0

In [5]:
a.var()

200.0

In [7]:
# variance with dtype
np.var(a, dtype= int)

200

In [9]:
#for 2-D array
b = np.array([[100,1,600],[400,500,300],[700,200,900],[800,9,20]])
b

array([[100,   1, 600],
       [400, 500, 300],
       [700, 200, 900],
       [800,   9,  20]])

In [11]:
# without axis
np.var(b)

95033.91666666667

In [13]:
# without axis with datatype
np.var(b, dtype = int)

95034

In [15]:
# with axis = 0 (row vise)
np.var(b, axis=0)

array([ 75000.  ,  41014.25, 108075.  ])

In [17]:
# with axis = 1 (column vise) and dtype
np.var(b, axis=1, dtype=int)

array([ 68734,   6666,  86666, 137133])