In [1]:
import numpy as np

#iterating 1-D Array
a = np.arange(10,40,2)
for i in np.nditer(a):
    print(i)

10
12
14
16
18
20
22
24
26
28
30
32
34
36
38


In [3]:
#iterating 2-D Array
a = np.array([[10,40,2],[1,50,2],[60,100,3]])
for i in np.nditer(a):
    print(i)

10
40
2
1
50
2
60
100
3


In [4]:
#iterating 3-D Array
a = np.array([[[10,40,2],[1,50,2]],[[60,100,3],[20,100,3]]])
for i in np.nditer(a):
    print(i)

10
40
2
1
50
2
60
100
3
20
100
3


In [18]:
#iterating elements of sliced Array
a = np.array([[[10,40,2],[1,50,2]],[[60,100,3],[20,100,3]]])
print(a)
b= a[:1,:1]
print("\nb value ==>\n " , b)
for i in np.nditer(b):
    print(i)

[[[ 10  40   2]
  [  1  50   2]]

 [[ 60 100   3]
  [ 20 100   3]]]

b value ==>
  [[[10 40  2]]]
10
40
2


In [26]:
#iterating elements of an Array of required data type
c = np.array([[[10,40,2],[1,50,2]],[[60,100,3],[20,100,3]]])
for i in np.nditer(c,flags=['buffered'], op_dtypes=['float64']):
    print(i)

10.0
40.0
2.0
1.0
50.0
2.0
60.0
100.0
3.0
20.0
100.0
3.0
