In [5]:
import numpy as np

#creating 1-D array
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a.ndim

1

In [9]:
a.shape

(10,)

In [11]:
a.dtype

dtype('int32')

In [13]:
a.size

10

In [15]:
#creating 1-D array values in between 10 to 20
b= np.arange(10,20)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
#creating 1-D array values in between 10 to 20 with steps 2
c= np.arange(10,20,2)
c

array([10, 12, 14, 16, 18])

In [37]:
d= np.arange(10,22,2, dtype = float)
d

array([10., 12., 14., 16., 18., 20.])

In [39]:
#reshape to make it 2-D array
np.reshape(d,(2,3))

array([[10., 12., 14.],
       [16., 18., 20.]])