In [3]:
import numpy as np

#creating an 1-D array using list
l=[10,20,30,40]
a = np.array(l)
a

array([10, 20, 30, 40])

In [5]:
#creating an array using tuple
t = (50,60,70,80)
b= np.array(t)
b

array([50, 60, 70, 80])

In [7]:
#Get dimension of array
a.ndim

1

In [9]:
#Get the shape of an array
a.shape

(4,)

In [11]:
#Get size of an array
a.size

4

In [13]:
#check type of element present in an array
a.dtype

dtype('int32')

In [15]:
#creating 2-D Array using list
td = [[10,20,30],[40,50,60],[70,80,90]]
tda = np.array(td)
tda

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [17]:
# Get dimension of 2-D array
tda.ndim

2

In [19]:
# Get type of array
type(tda)

numpy.ndarray

In [21]:
# Get type of element present in an 2-D array
tda.dtype

dtype('int32')

In [23]:
#Get the shape of a 2-D array
tda.shape

(3, 3)

In [25]:
#Get size of a 2-D array
tda.size

9

In [33]:
#creating 3-D array using list
th = [[[10,20,30],[40,50,60],[70,80,90]], [['A','B','C'],['D','E','F'],['G','H','I']]]
tha = np.array(th, dtype = object)
tha

array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]],

       [['A', 'B', 'C'],
        ['D', 'E', 'F'],
        ['G', 'H', 'I']]], dtype=object)

In [39]:
tha.ndim

3

In [47]:
#if number of rows doesnot match in both 2-D arrays
ther = [[[10,20,30],[40,50,60],[70,80,90]], [['A','B','C'],['D','E','F']]]
the = np.array(ther, dtype = object)
the

array([list([[10, 20, 30], [40, 50, 60], [70, 80, 90]]),
       list([['A', 'B', 'C'], ['D', 'E', 'F']])], dtype=object)

In [49]:
the.ndim

1

In [57]:
#if number of columns doesnot match in both 2-D arrays
thc = [[[10,20,30],[40,50,60],[70,80,90]], [['A','C'],['D','F'],['G','I']]]
thr = np.array(thc, dtype = object)
thr

array([[list([10, 20, 30]), list([40, 50, 60]), list([70, 80, 90])],
       [list(['A', 'C']), list(['D', 'F']), list(['G', 'I'])]],
      dtype=object)

In [55]:
thr.ndim

2

In [28]:
ele = (45,2.0,True,'Hello')
np.array(ele)

array(['45', '2.0', 'True', 'Hello'], dtype='<U32')

In [30]:
np.array(ele,dtype = object)

array([45, 2.0, True, 'Hello'], dtype=object)