In [1]:
import numpy as np

#creating an 1-D array using list
l=[10,20,30,40]
a = np.array(l)
a

array([10, 20, 30, 40])

In [2]:
#creating an array using tuple
t = (50,60,70,80)
b= np.array(t)
b

array([50, 60, 70, 80])

In [5]:
#Get dimension of array
a.ndim

1

In [13]:
#Get the shape of an array
a.shape

(4,)

In [14]:
#Get size of an array
a.size

4

In [6]:
#check type of element present in an array
a.dtype

dtype('int64')

In [7]:
#creating 2-D Array using list
td = [[10,20,30],[40,50,60],[70,80,90]]
tda = np.array(td)
tda

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [8]:
# Get dimension of 2-D array
tda.ndim

2

In [9]:
# Get type of array
type(tda)

numpy.ndarray

In [10]:
# Get type of element present in an 2-D array
tda.dtype

dtype('int64')

In [11]:
#Get the shape of a 2-D array
tda.shape

(3, 3)

In [12]:
#Get size of a 2-D array
tda.size

9