In [2]:
import numpy as np

#creating 1-D array
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a.ndim

1

In [5]:
a.shape

(10,)

In [6]:
a.dtype

dtype('int64')

In [7]:
a.size

10

In [8]:
#creating 1-D array values in between 10 to 20
b= np.arange(10,20)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
#creating 1-D array values in between 10 to 20 with steps 2
c= np.arange(10,20,2)
c

array([10, 12, 14, 16, 18])

In [10]:
#creating 1-D array values in between 10 to 20 with steps 2 but defining dtype
d= np.arange(10,20,2, dtype = float)
d

array([10., 12., 14., 16., 18.])