In [1]:
import numpy as np

#creating ones 1-d array
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [2]:
#creating ones 2-d array
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
#creating ones 3-d array
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
np.ones((2,2,3)).size

12

In [8]:
#creating ones 4-d array
np.ones((2,2,2,3),dtype=int)

array([[[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]]])

In [9]:
#creating ones 5-d array
np.ones((5,2,2,3),dtype=int)

array([[[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]]])

In [10]:
np.ones((5,2,2,3),dtype=int).shape

(5, 2, 2, 3)

In [11]:
np.ones((5,2,2,3),dtype=int).size

60